system:
    appName: openai-wechat
    pidFile: config/bin/openai-wechat.lock

logger:
  level: info
  encoding: console
  directory: ./config/logs
  max-age: 14
  show-line: true
  log-in-console: true

open-ai:
  api-key: ""
  base-url: https://free.churchless.tech/v1

wx-robot:
  auto-pass: true
  session-timeout: 900
  storage-path: config/storage.json
  retry-num: 3