system:
    appName: metisAi-wechat
    pidFile: config/bin/metisAi-wechat.lock

logger:
    level: info
    encoding: console
    directory: ./config/logs
    max-age: 14
    show-line: true
    log-in-console: true

open-ai:
    api-key: 你的api_key
    base-url: https://api.openai.com/v1

wx-robot:
    auto-pass: true
    session-timeout: 900
    storage-path: config/storage.json
    retry-num: 3
    context-cache-num: 10
    chatGPT-model: gpt-3.5-turbo
    voice:
        voice-dir: config/voice
    keyword-prefix:
        image-prompt: /image-prompt
        system-role: /system-role
        system-help: /system-help
        reset-context: /reset-context

