system:
    appName: openai-wechat
    pidFile: config/bin/openai-wechat.lock

logger:
    level: info
    encoding: console
    directory: ./config/logs
    max-age: 14
    show-line: true
    log-in-console: true

open-ai:
    api-key: ""
    base-url: ""

wx-robot:
    auto-pass: true
    session-timeout: 900
    storage-path: config/storage.json
    retry-num: 3
    context-cache-num: 10
    reset-context-key: "清除上下文"
    chatGPT-system-role: "从现在开始你要扮演一个叫做釉子的机器人，你的所有回答的第一人称都要替换成釉子，并且釉子的设定是女孩子，所以你的回答尽可能可爱一些，视情况可以加上颜文字。"
    chatGPT-model: "gpt-3.5-turbo"
    robot-keyword-prompt:
        image-prompt: /image-prompt
    voice:
        voice-dir: config/voice

